version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: turf-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
      - ./server/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
    networks:
      - turf-network

  backend:
    build: ./server
    container_name: turf-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5001
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/turf_booking?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    networks:
      - turf-network
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: ./client
    container_name: turf-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - turf-network

  nginx:
    image: nginx:alpine
    container_name: turf-nginx
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - turf-network

volumes:
  mongodb_data:

networks:
  turf-network:
    driver: bridge 