services:
  postgres:
    image: postgres:15
    container_name: turf-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: turf_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - turf-network

  backend:
    build: ./server
    container_name: turf-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5001
      - DATABASE_URL=postgresql://postgres:password123@postgres:5432/turf_booking
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    networks:
      - turf-network
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: ./client
    container_name: turf-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - turf-network

  nginx:
    image: nginx:alpine
    container_name: turf-nginx
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - turf-network

volumes:
  postgres_data:

networks:
  turf-network:
    driver: bridge 