apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: namandhoot26/turf-booking-backend:latest
        ports:
        - containerPort: 5001
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:password123@postgres-service:5432/turf_booking"
        - name: JWT_SECRET
          value: "your-secret-key"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  selector:
    app: backend
  ports:
  - port: 5001
    targetPort: 5001
  type: ClusterIP 