apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: turf-booking
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-dockerhub-username/turf-booking-backend:latest
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: turf-booking-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: turf-booking-config
              key: PORT
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: turf-booking-config
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: turf-booking-secrets
              key: JWT_SECRET
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/ready
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: turf-booking
spec:
  selector:
    app: backend
  ports:
  - port: 5001
    targetPort: 5001
  type: ClusterIP 