apiVersion: v1
kind: Secret
metadata:
  name: turf-booking-secrets
  namespace: turf-booking
type: Opaque
data:
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  MONGODB_USERNAME: YWRtaW4=
  MONGODB_PASSWORD: cGFzc3dvcmQxMjM= 